@echo off
echo Getting GatherSystemInfo script...
powershell -Command "Invoke-WebRequest -Uri 'https://vel2006.github.io/Errox_CMD/GatherSystemInfo.bat' -OutFile 'GatherSystemInfo.bat'
echo Getting BatchTerminal script...
powershell -Command "Invoke-WebRequest -Uri 'https://vel2006.github.io/Errox_CMD/BatchTerminal.bat' -OutFile 'BatchTerminal.bat'
echo Getting InstallPython script...
powershell -Command "Invoke-WebRequest -Uri 'https://vel2006.github.io/Errox_CMD/InstallPython.bat' -OutFile 'InstallPython.bat'
echo Getting Main script...
powershell -Command "Invoke-WebRequest -Uri 'https://vel2006.github.io/Errox_CMD/main.bat' -OutFile 'main.bat'
